depth_anything_config:
  model:
    model_type: "metric"
    model_size: "vits"
    model_path: "/scratchdata/depth_anything_v2_metric_hypersim_vits.pth"
  camera:
    camera_type: "gemini_2l"
    min_range: 0.0
    max_range: 65.535
    min_reliable_range: 0.3
    max_reliable_range: 7.0
    rgb_topic: "/camera/color/image_raw"
    depth_topic: "/camera/depth/image_raw"